train:
  _target_: src.datasets.LJSpeechDataset
  data_dir: "data/wavs"
  audio_max_len: 8192
  limit: 2
  random: False
val:
  _target_: src.datasets.LJSpeechDataset
  data_dir: "data/val_wavs"
  limit: 2
  audio_max_len: 8192
  random: True
