train:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.utils.audio_utils.MelSpectrogramConfig
inference:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.utils.audio_utils.MelSpectrogramConfig
